# Remote Desktop Setup

This repository contains a Docker setup for Apache Guacamole, a clientless remote desktop gateway. This setup allows you to access RDP sessions via a web interface.

## Setup Instructions

1. **Clone the Repository**

    ```bash
    git clone https://github.com/<your-username>/remote-desktop-setup.git
    cd remote-desktop-setup
    ```

2. **Run the Setup Script**

    Ensure Docker and Docker Compose are installed on your machine. Then, run:

    ```bash
    ./setup.sh
    ```

3. **Access Guacamole**

    Open your web browser and navigate to:

    ```
    http://localhost:8080/guacamole
    ```

4. **Login**

    Default login credentials are:

    - **Username:** `guacadmin`
    - **Password:** `guacadmin`

    Make sure to change these credentials and configure your RDP connections through the Guacamole web interface.

## Notes

- **Security:** Ensure to secure your Guacamole instance by following best security practices.
- **Customization:** Modify `docker-compose.yml` and `setup.sh` as needed to fit your requirements.

## License

This project is licensed under the MIT License. See the [LICENSE](LICENSE) file for details.

